#! /bin/bash
set -euo pipefail

ENV=${1:-dev}

sbt assembly

docker build -t mtchd/connect4:"${ENV}" .

# Get password

PASSWORD=$(aws kms decrypt --ciphertext-blob fileb://"$(dirname "$0")"/../encrypted/docker.encrypted --region ap-southeast-2 \
        --query Plaintext \
        --output text | base64 --decode)

echo "${PASSWORD}" | docker login --username mtchd --password-stdin

docker push mtchd/connect4