#!/usr/bin/env bash

set -euo pipefail

# Set Up
yum update -y
yum install docker -y
usermod -a -G docker ec2-user
service docker start

docker pull mtchd/connect4:prod

# Base64 takes a lowercase -d on linux
ENCRYPTED_DB_PASS=AQICAHhmLC/OEYZUyfRG86YuTDDXQX6tMI11YGBotbwolXT/PwGsO7qzsVKYgdU3+57hVaEcAAAAiTCBhgYJKoZIhvcNAQcGoHkwdwIBADByBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDMpxiHptfWFEJcjungIBEIBFtUN6h9H7/scpTpd698L1iTCtvCAmDiKrPDv/3uMBGEzVkWBQfnTUEZWp5PzxUIQm60dfCEKPz4i7etLqIWlbyGEDzj/n
echo ${ENCRYPTED_DB_PASS} | base64 -d > db.encrypted

ENCRYPTED_PROD_SLACK_TOKEN=AQICAHhmLC/OEYZUyfRG86YuTDDXQX6tMI11YGBotbwolXT/PwHZksn7tWDDaTqU+C4yQJUaAAAAljCBkwYJKoZIhvcNAQcGoIGFMIGCAgEAMH0GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMgKs/WZmBmioiYfXJAgEQgFDM5mt4xJAQ8sY/7TKfPOORp/t28xR2hVVbBv4rBXD7Qvo9tLNjElekaVsb+L/rMZ1xeTVGhZo7DPCuug4KnxSs64R8TkJhVoNlrA8N3HGXLw==
echo ${ENCRYPTED_PROD_SLACK_TOKEN} | base64 -d > prod.encrypted

echo "Decrypting slack api key..."
SLACK_TOKEN=$(aws kms decrypt --ciphertext-blob fileb://prod.encrypted --region ap-southeast-2 \
        --query Plaintext \
        --output text | base64 --decode)

echo "Decrypting database password..."
DB_PASS=$(aws kms decrypt --ciphertext-blob fileb://db.encrypted --region ap-southeast-2 \
        --query Plaintext \
        --output text | base64 --decode)

echo "Starting connect 4..."
docker run -d --rm -e SLACK_TOKEN="${SLACK_TOKEN}" -e DB_PASS="${DB_PASS}" mtchd/connect4
