#!/usr/bin/env bash

set -euo pipefail

ENV=${1:-dev}

# Set Up
sudo yum update -y
sudo yum install docker -y
sudo usermod -a -G docker ec2-user
sudo service docker start

sudo docker pull mtchd/connect4

echo "Decrypting slack api key..."
SLACK_TOKEN=`aws kms decrypt --ciphertext-blob fileb://${ENV}.encrypted --region ap-southeast-2 \
        --query Plaintext \
        --output text | base64 --decode`

echo "Decrypting database password..."
DB_PASS=`aws kms decrypt --ciphertext-blob fileb://db.encrypted --region ap-southeast-2 \
        --query Plaintext \
        --output text | base64 --decode`

echo "Starting connect 4..."
sudo docker run -d --rm -e SLACK_TOKEN=${SLACK_TOKEN} -e DB_PASS=${DB_PASS} mtchd/connect4