#!/usr/bin/env bash

set -euo pipefail

terraform init

echo "Decrypting db password..."
DB_PASS=$(aws kms decrypt --ciphertext-blob fileb://encrypted/db.encrypted --region ap-southeast-2 \
        --query Plaintext \
        --output text | base64 --decode)

# Removed auto-approve while I'm not using Buildkite
echo "Terraform apply running..."
terraform apply \
        -var 'dbPassword='"${DB_PASS}"''